working client generating and login - so script should work, even with mesh-vpn and ibss and AP

diff --git a/files/lib/gluon/v14tov15-helper/v14tov15-helper b/files/lib/gluon/v14tov15-helper/v14tov15-helper
--- a/files/lib/gluon/v14tov15-helper/v14tov15-helper
+++ b/files/lib/gluon/v14tov15-helper/v14tov15-helper
@@ -9,20 +9,21 @@
 # more Info: https://github.com/viisauksena/gluon-v14tov15-helper
 
 # some cron debug help , write in ram 
-echo "v14v15 helper successfully startet at $(date +%y%m%d_%H%M)" > /tmp/v14_lastrun
+echo "v14v15 helper successfully start at $(date +%y%m%d_%H%M)" > /tmp/v14_lastrun
 
 # if your script is dependend on autoupdater, do only uptate if its realy enabled!
 if [ $(uci get autoupdater.settings.enabled) = 0 ]; then exit 1; fi
 
 # check gw
 # quick and dirty do it 4 times every 30 seconds
-# to prevent false positives
-gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 11; fi ; sleep 30
-gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 12; fi ; sleep 30 
-gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 13; fi ; sleep 30 
-gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 14; fi
+# to highly prevent false positives
+gwl=$(batctl gwl -H -n |grep gateways | wc -l) ; if [ $gwl != 0 ]; then exit 11; fi ; sleep 30
+gwl=$(batctl gwl -H -n |grep gateways | wc -l) ; if [ $gwl != 0 ]; then exit 12; fi ; sleep 30 
+gwl=$(batctl gwl -H -n |grep gateways | wc -l) ; if [ $gwl != 0 ]; then exit 13; fi ; sleep 30 
+gwl=$(batctl gwl -H -n |grep gateways | wc -l) ; if [ $gwl != 0 ]; then exit 14; fi
 
-# if wlan0 is desired (only in configmode where we do not want autoupdater)
+# if wlan0 is desired 
+# (only in configmode where we do not want autoupdater, but its possible to run from there too)
 # ifconfig wlan0 up
 # iw wlan0 connect freiburg.freifunk.net
 # udhcp -b -i wlan0 
@@ -34,23 +35,40 @@ many=$(iwinfo phy0 scan |grep $ffssid | wc -l)
 
 # connect to freifunk and get dhcp lease
 if [ $many != 0 ]; then
+	# generate foo mac, and alternative if failing
+        foomac=42:42:$(iwinfo | grep Acc |head -n1 |grep -oE '[^ ]+$' |cut -d":" -f 3-6)
+	: ${foomac:=42:42:23:$(date +%H:%M:%S)}
+	# make hw if ready
 	iw phy0 interface add update type managed
-	ifconfig update up
-	iw update connect $ffssid
+        ifconfig update hw ether $foomac
+        ifconfig update up
+	# install new if in /etc/config/wireless
+	uci set wireless.update_radio0=wifi-iface
+	uci set wireless.update_radio0.ifname=update
+	uci set wireless.update_radio0.network=update
+	uci set wireless.update_radio0.disabled=0
+	uci set wireless.update_radio0.device=radio0
+	uci set wireless.update_radio0.mode=sta
+	uci set wireless.update_radio0.macaddr=$foomac
+	uci set wireless.update_radio0.ssid=$ffssid
+	uci comit
+	# restart wifi and get ip 
+	wifi; sleep 2;
 	udhcpc -B -b -i update
 fi
 
 # just in case v6 dns resolving is strange
-# TODO
+# TODO : check everything
 # something is wrong here .. if IFace is generated and all autoupdater /wget will throw v6 permission denied
-echo 1 > /proc/sys/net/ipv6/conf/all/accept_ra
-echo 1 > /proc/sys/net/ipv6/conf/all/autoconf
+# echo 1 > /proc/sys/net/ipv6/conf/all/accept_ra
+# echo 1 > /proc/sys/net/ipv6/conf/all/autoconf
 
-# just in case dns doesnt work , add extra foo
-echo "nameserver 10.60.0.100" >> /etc/resolv.conf
-echo "nameserver 4.2.2.2" >> /etc/resolv.conf
+# just in case dns doesnt work , believed not needed
+# echo "nameserver 10.60.0.100" >> /etc/resolv.conf
+# echo "nameserver 4.2.2.2" >> /etc/resolv.conf
 
-# here comes the funny part 
+# here comes the funny part, regular
+# also means update server MUST be reachable as client
 autoupdater -f
 
 # alternativly load and verify a bat v15 version in ram and change existing batman on node
@@ -59,7 +77,11 @@ autoupdater -f
 # https://forum.freifunk.net/t/batman-v14-zu-v15-upgrade-gluon-package/10808/6?u=fuzzle
 
 # if autoupdater and first checks above run correct you should never reach this point
-# better safe than sorry - taking new IF down
+# better safe than sorry - taking new IF down and remove wireless entrys
+# could be while download and/or manifest-signing or checksum check fails
 iw update del
+uci delete wireless.update_radio0
+uci commit
+logger "something strange happens - could not autoupdate via v14v15 helper"
 exit 21
 
